### ISSUE TITLE
pip install fails when using a remote

### ISSUE THREAD

**Issue by shirouto** [purescript-python/installer#2]
When using a remote repository to install the package, it appears that the install script runs into some race or permission issue (I am not that familiar with setuptools to quickly trace the dance). Otherwise, cloning and running `pip3 install -e .` works just fine.

```
 [hello-pyps-36JxoFrK-py3.6] $ pip3 install git+https://github.com/purescript-python/installer
Collecting git+https://github.com/purescript-python/installer
  Cloning https://github.com/purescript-python/installer to /tmp/pip-uvebzh1m-build
Installing collected packages: pspy-placeholder
  Running setup.py install for pspy-placeholder ... error
    Complete output from command /home/user/.cache/pypoetry/virtualenvs/hello-pyps-36JxoFrK-py3.6/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-uvebzh1m-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6zftvyfq-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.cache/pypoetry/virtualenvs/hello-pyps-36JxoFrK-py3.6/include/site/python3.6/pspy-placeholder:
    running install
    running bdist_egg
    running egg_info
    writing pspy_proxy.egg-info/PKG-INFO
    writing dependency_links to pspy_proxy.egg-info/dependency_links.txt
    writing entry points to pspy_proxy.egg-info/entry_points.txt
    writing requirements to pspy_proxy.egg-info/requires.txt
    writing top-level names to pspy_proxy.egg-info/top_level.txt
    reading manifest file 'pspy_proxy.egg-info/SOURCES.txt'
    writing manifest file 'pspy_proxy.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_py
    creating build/bdist.linux-x86_64/egg
    creating build/bdist.linux-x86_64/egg/pspy_proxy
    copying build/lib/pspy_proxy/__init__.py -> build/bdist.linux-x86_64/egg/pspy_proxy
    copying build/lib/pspy_proxy/proxy.py -> build/bdist.linux-x86_64/egg/pspy_proxy
    byte-compiling build/bdist.linux-x86_64/egg/pspy_proxy/__init__.py to __init__.cpython-36.pyc
    byte-compiling build/bdist.linux-x86_64/egg/pspy_proxy/proxy.py to proxy.cpython-36.pyc
    creating build/bdist.linux-x86_64/egg/EGG-INFO
    copying pspy_proxy.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pspy_proxy.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pspy_proxy.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pspy_proxy.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pspy_proxy.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pspy_proxy.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pspy_proxy.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    creating 'dist/pspy_proxy-0.1-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
    removing 'build/bdist.linux-x86_64/egg' (and everything under it)
    Processing pspy_proxy-0.1-py3.6.egg
    removing '/home/user/.cache/pypoetry/virtualenvs/hello-pyps-36JxoFrK-py3.6/lib/python3.6/site-packages/pspy_proxy-0.1-py3.6.egg' (and everything under it)
    creating /home/user/.cache/pypoetry/virtualenvs/hello-pyps-36JxoFrK-py3.6/lib/python3.6/site-packages/pspy_proxy-0.1-py3.6.egg
    Extracting pspy_proxy-0.1-py3.6.egg to /home/user/.cache/pypoetry/virtualenvs/hello-pyps-36JxoFrK-py3.6/lib/python3.6/site-packages
    pspy-proxy 0.1 is already the active version in easy-install.pth
    Installing pspy-blueprint script to /home/user/.cache/pypoetry/virtualenvs/hello-pyps-36JxoFrK-py3.6/bin

    [...]

    Finished processing dependencies for pspy-proxy==0.1
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Downloading binaries from purescript-python/purescript-python...
    Binaries downloaded.
    Traceback (most recent call last):
      File "install_binary.py", line 129, in <module>
        get_binary()
      File "install_binary.py", line 125, in get_binary
        zf.extract(exe, path=str(out_path))
      File "/usr/lib/python3.6/zipfile.py", line 1507, in extract
        return self._extract_member(member, path, pwd)
      File "/usr/lib/python3.6/zipfile.py", line 1578, in _extract_member
        open(targetpath, "wb") as target:
    PermissionError: [Errno 13] Permission denied: '/tmp/pip-uvebzh1m-build/pspy_placeholder/pspy-blueprint'
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build/lib/pspy_placeholder
    copying pspy_placeholder/__init__.py -> build/lib/pspy_placeholder
    copying pspy_placeholder/pspy-blueprint -> build/lib/pspy_placeholder
    error: could not open 'pspy_placeholder/pspy-blueprint': Permission denied

    ----------------------------------------
Command "/home/user/.cache/pypoetry/virtualenvs/hello-pyps-36JxoFrK-py3.6/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-uvebzh1m-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6zftvyfq-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.cache/pypoetry/virtualenvs/hello-pyps-36JxoFrK-py3.6/include/site/python3.6/pspy-placeholder" failed with error code 1 in /tmp/pip-uvebzh1m-build/

```

**Comment by thautwarm** [comment]
Hello, this is because we have to download prebuilt binary file and put it in a python package, and the permission to write `tmp` is not allowed:

> PermissionError: [Errno 13] Permission denied: '/tmp/pip-uvebzh1m-build/pspy_placeholder/pspy-blueprint'

We're invesgating, and it's okay for you to clonrle this repo first and use pip on the local repo.

**Comment by thautwarm** [comment]
Prrviously we download binary file to `~/.local/bin` but this means the binary file will be shared to all python virtualenvs, which is kind of bad.
So now we're trying to bundle the binary with python package.
